name: Publish latest image
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login into registry Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          cache-from: type=gha,scope=${{ github.ref }}_sirherobrine23_docker
          cache-to: type=gha,mode=max,scope=${{ github.ref }}_sirherobrine23_docker
          platforms: "linux/amd64,linux/arm64"
          tags: |
            ghcr.io/sirherobrine23/mydockerimage:latest
